# Generated by Django 4.2.5 on 2023-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='company_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='company_info',
            name='company_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
