# Generated by Django 4.2.5 on 2023-09-23 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_alter_company_info_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlist', 'Shortlist'), ('Interview', 'Interview'), ('Reject', 'Reject')], default='Pending', max_length=50)),
                ('match', models.CharField(default='0 Star', max_length=50)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='employer.jobs')),
                ('seeker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
