# Generated by Django 4.2.5 on 2023-09-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_jobs_created_at_jobs_updated_at_alter_jobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_preferences',
            name='employer',
        ),
        migrations.AlterField(
            model_name='job_reviews',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobs'),
        ),
    ]
