# Generated by Django 4.2.5 on 2023-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='hiring_city',
            field=models.CharField(default='khi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='hiring_country',
            field=models.CharField(default='pakistan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
