# Generated by Django 4.2.5 on 2023-09-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_seeker_cv_alter_projects_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_info',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
